---
- name: Deploy flask app
  hosts: g1
  become: yes

  tasks:
    - name: Add the default centos repository
      yum_repository:
        name: epel
        description: EPEL YUM repo
        baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
        state: present

    - name: Install packages
      package:
        name:
          - python3
          - python3-pip
          - git

    - name: Create the destination folder
      file:
        path: /opt/flaskwebapp
        state: directory

    - name: Clone the repository
      git:
        repo: https://github.com/elvisomofezi/Flask.git
        dest: /opt/flaskwebapp

    - name: Install flask
  pip:
    name: flask
    
    -name: Start flask Service
    service:
     name: flask
     state: started
     enabled: yes
